# Generated by Django 5.2 on 2025-05-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('matching_type', models.CharField(choices=[('1:1', '1:1'), ('N:N', 'N:N')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
