# Generated by Django 5.2 on 2025-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_student_council'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_council',
        ),
        migrations.AddField(
            model_name='user',
            name='calendar_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student_council',
            field=models.BooleanField(default=False),
        ),
    ]
