# Generated by Django 5.2 on 2025-06-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_student_council_user_calendar_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calendar_color',
        ),
    ]
