# Generated by Django 5.2 on 2025-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_calendar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buddy_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
