# Generated by Django 5.2 on 2025-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_buddy_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyprofile',
            name='student_type',
            field=models.CharField(choices=[('Korean', '한국 학생'), ('International', '국제 학생')], default='Korean', max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='buddyprofile',
            name='matching_type',
            field=models.CharField(choices=[('1:1', '1:1')], max_length=3),
        ),
    ]
