# Generated by Django 5.2 on 2025-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_buddyprofile_student_type_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('IBA', 'International Business Administration'), ('MSE', 'Mobile Systems Engineering'), ('BME', 'Bio and Material Engineering'), ('KST', 'Korea Studies'), ('AFM', 'Acting & Filmmaking'), ('GCE', 'Global Core Education'), ('PID', 'Primus International Department')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
