# Generated by Django 5.2 on 2025-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyprofile',
            name='student_type',
        ),
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(choices=[('Korean', '한국 학생'), ('International', '국제 학생')], default='Korean', max_length=13),
        ),
    ]
