# Generated by Django 5.2 on 2025-06-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_student_council_user_calendar_color_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='student_council',
        ),
        migrations.DeleteModel(
            name='StudentCouncil',
        ),
    ]
