# Generated by Django 5.2 on 2025-06-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='event_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
