# Generated by Django 5.2 on 2025-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_boardpost_event_end_boardpost_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='original_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='translated_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='original_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='translated_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
