# Generated by Django 5.2 on 2025-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_boardpost_original_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='board_images',
            field=models.ImageField(blank=True, null=True, upload_to='board_images/'),
        ),
    ]
