# Generated by Django 5.2 on 2025-06-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_boardpostimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpost',
            name='board_images',
        ),
        migrations.AlterField(
            model_name='boardpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_images', to='board.boardpost'),
        ),
    ]
